routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
//Route::get('/admin','Admin\\DashboardController@index')->name('admin.dashboard');
//Route::get('/admin/product','Admin\\ProductController@index')->name('admin.product');
//Route::get('/admin/product/create','Admin\\ProductController@create')->name('admin.product.create');
//Route::post('/admin/product/create','Admin\\ProductController@store')->name('admin.product.store');
//Route::get('/admin/product/edit/{id?}','Admin\\ProductController@edit')->name('admin.product.edit');
//Route::post('/admin/product/edit','Admin\\ProductController@update')->name('admin.product.update');
//Route::get('/admin/product/delete/{pid?}','Admin\\ProductController@delete')->name('admin.product.delete');
//Route::get('/admin/category','Admin\\CategoryController@index')->name('admin.category');
//Route::get('/admin/category/create','Admin\\CategoryController@create')->name('admin.category.create');
//Route::post('/admin/category/create','Admin\\CategoryController@store')->name('admin.category.store');
//Route::get('/admin/category/edit/{catid?}','Admin\\CategoryController@edit')->name('admin.category.edit');
//Route::post('/admin/category/edit','Admin\\CategoryController@update')->name('admin.category.updaye');
Route::group(['namespace' => 'Frontend\\'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/basket/add/{pid}', 'BasketController@add')->name('basket.add');
    Route::get('/basket', 'BasketController@show')->name('basket.show');
    Route::post('/basket/update', 'BasketController@update')->name('basket.update');
    Route::get('/basket/checkout', 'BasketController@checkout')->name('basket.checkout');
    Route::get('/register', 'AuthController@showRegister')->name('registerForm');
    Route::post('/register', 'AuthController@doRegister')->name('doRegister');
    Route::get('/login', 'AuthController@showLogin')->name('loginForm');
    Route::post('/login', 'AuthController@doLogin')->name('doLogin');
    Route::get('logout', 'AuthController@doLogOut')->name('LogOut');
    Route::get('product/{pid}', 'ProductController@singlePage')->name('product.single');
});

Route::group(['prefix' => 'admin/', 'namespace' => 'Admin\\'], function () {
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::get('product', 'ProductController@index')->name('admin.product');
    Route::get('product/create', 'ProductController@create')->name('admin.product.create');
    Route::post('product/create', 'ProductController@store')->name('admin.product.store');
    Route::get('product/edit/{id?}', 'ProductController@edit')->name('admin.product.edit');
    Route::post('product/edit', 'ProductController@update')->name('admin.product.update');
    Route::get('product/delete/{pid?}', 'ProductController@delete')->name('admin.product.delete');
    Route::get('category', 'CategoryController@index')->name('admin.category');
    Route::get('category/create', 'CategoryController@create')->name('admin.category.create');
    Route::post('category/create', 'CategoryController@store')->name('admin.category.store');
    Route::get('category/edit/{catid?}', 'CategoryController@edit')->name('admin.category.edit');
    Route::post('category/edit', 'CategoryController@update')->name('admin.category.updaye');
    Route::get('attribute', 'AttributeController@index')->name('admin.attribute');
    Route::get('attribute/create', 'AttributeController@create')->name('admin.attribute.create');
    Route::post('attribute/create', 'AttributeController@store')->name('admin.attribute.store');
    Route::get('attributecategory', 'AttributeController@index_category')->name('admin.attributecategory');
    Route::get('attributecategory/create', 'AttributeController@create_category')->name('admin.attributecategory.create');
    Route::post('attributecategory/create', 'AttributeController@store_category')->name('admin.attributecategory.store');
    Route::get('attributetype', 'AttributeController@index_type')->name('admin.attributetype');
    Route::get('attributetype/create', 'AttributeController@create_type')->name('admin.attributetype.create');
    Route::post('attributetype/create', 'AttributeController@store_type')->name('admin.attributetype.store');
    Route::post('product/attribute/{pid}', 'AttributeController@getCategoryAttribute')->name('admin.attributetype.ajax');
    //Order Route
    Route::get('order', 'OrderController@index')->name('admin.order');
    Route::get('order/create', 'OrderController@create')->name('admin.order.create');
    Route::get('order/approve/{order_id}', 'OrderController@approve')->name('admin.order.approve');
    Route::get('order/pay/{order_code}', 'OrderController@payment')->name('admin.order.pay');

});

app/Models/Order/Order.php
<?php

namespace App\Models\Order;


use App\Models\User;
use App\Presenters\Contract\Presentable;
use App\Presenters\Order\OrderPresenter;
use App\Services\Payment\PaymentType;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use Presentable;
    protected $primaryKey = 'order_id';
    protected $guarded = ['order_id'];
    public $presenter = OrderPresenter::class;

    public function user()
    {
        return $this->belongsTo(User::class, 'order_user_id');
    }

    public function order_items()
    {
        return $this->hasMany(OrderItem::class, 'order_item_order_id');
    }

    public function order_logs()
    {
        return $this->hasMany(OrderLog::class, 'order_log_order_id');
    }

    public function getPaymentMethodAttribute()
    {
        $type = PaymentType::getPaymentType();
        return $type[$this->order_payment_method];
    }

    public function updateStatus(int $status)
    {
        $statuses=OrderStatus::getAllOrderStatus();
        if(!in_array($status,array_keys($statuses))){
            return false;
        }
        $this->order_status=$status;
        $this->save();
    }

}

app/Models/Order/OrderItem.php
<?php

namespace App\Models\Order;

use Illuminate\Database\Eloquent\Model;

class OrderItem extends Model
{
    protected $primaryKey = 'order_item_id';
    protected $guarded = ['order_item_id'];

    public function Order()
    {
        return $this->belongsTo(Order::class,'order_item_order_id');
    }
}

app/Models/Order/OrderLog.php
<?php

namespace App\Models\Order;

use App\Models\Order\Order;
use Illuminate\Database\Eloquent\Model;

class OrderLog extends Model
{
    protected $primaryKey='order_log_id';
    protected $guarded=['order_log_id'];

    public function order()
    {
        return $this->belongsTo(Order::class,'order_log_order_id');
    }
}

app/Models/Order/OrderStatus.php
<?php
/**
 * Created by PhpStorm.
 * User: navid
 * Date: 6/12/18
 * Time: 8:36 AM
 */

namespace App\Models\Order;


class OrderStatus
{
    const UNPAID = 0;
    const PAID = 1;
    const CANCELED = 2;
    const REFUNDED = 3;
    const DELIVERED = 4;
    const SENT = 5;
    const SEND_READY = 6;

    public static function getAllOrderStatus()
    {
        return [
            self::UNPAID => 'پرداخت نشده',
            self::PAID => 'پرداخت شده',
            self::CANCELED => 'کنسل شده',
            self::REFUNDED => 'برگشت داده شده',
            self::DELIVERED => 'تحویل داده شده',
            self::SENT => 'ارسال شده',
            self::SEND_READY => 'آماده ارسال',
        ];
    }

    public static function getOrderStatus(int $status)
    {
        return self::getAllOrderStatus()[$status];

    }

    public static function getOrderStatusCssClass(int $status)
    {
        return [
            self::UNPAID => 'primary',
            self::PAID => 'success',
            self::CANCELED => 'warning',
            self::REFUNDED => 'danger',
            self::DELIVERED => 'info',
            self::SENT => 'info',
            self::SEND_READY => 'info',
        ][$status];
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Events\Event;
use App\Events\OrderCreated;
use App\Jobs\SendInvoice;
use App\Models\Order\OrderStatus;
use App\Repositories\Order\OrderRepository;
use App\Services\Order\OrderService;
use App\Services\Payment\PaymentService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
    protected $orderRepository;
    protected $productRepository;
    protected $orderService;


    public function __construct()
    {
        $this->orderRepository = new OrderRepository();
        $this->orderService=new OrderService();

    }

    public function index()
    {
        $orders = $this->orderRepository->all(['user','order_items']);
        $title = 'لیست سفارش ها';
        return view('admin.order.index', compact('orders', 'title'));
    }

    public function create()
    {
//        $title = 'ایجاد سفارش جدید';
//        $allProduct=$this->productRepository->all();
//        return view('admin.order.create', compact('title','allProduct'));
        $orderService = new OrderService();
        $order = $orderService->create([
            'user_id' => 1,
            'total_amount' => 1500000,
            'order_discount' => 0,
            'order_items' => [
                [
                    'product_id' => 7,
                    'amount' => 500000,
                    'disount' => 0
                ], [
                    'product_id' => 8,
                    'amount' => 600000,
                    'disount' => 0
                ], [
                    'product_id' => 9,
                    'amount' => 700000,
                    'disount' => 0
                ],
            ]
        ]);

//        SendInvoice::dispatch($order)->delay(now()->addMinutes(10))->onQueue('email')->onConnection('sqs');
        event(new OrderCreated($order['order']));

    }

    public function payment(Request $request, $orderCode)
    {
        $orderInfo = $this->orderRepository->findBy(['order_code' => $orderCode], ['user']);
        $paymentService = new PaymentService();
        $paymentResult = $paymentService->pay($orderInfo);
    }

    public function approve(Request $request,$order_id)
    {
      $order_item=$this->orderRepository->find($order_id);
      $order_item->updateStatus(OrderStatus::PAID);
      $this->orderService->updateStatus($order_id,$order_item->order_status,OrderStatus::PAID);
    }
}

resources/views/admin/order/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ $title }}</h3>
                    @if (session('success'))
                        <div class="alert alert-success">
                            <p>دسته بندی جدید با موفقیت ثبت گردید</p>
                        </div>
                    @endif
                </div>
                <!-- /.box-header -->
                <!-- form start -->

                <form role="form" method="post">
                    {{ csrf_field() }}
                    <div class="box-body">
                        <div class="form-group">
                            <label for="category_title">عنوان دسته بندی :</label>
                            <input type="text" class="form-control" id="category_title" name="category_title"
                                   placeholder="عنوان دسته بندی را وارد نمایید">
                        </div>
                        <div class="form-group">
                            <label for="category_sub">محصول :</label>
                            {{--<select name="category_sub" id="category_sub">--}}
                                {{--<option value="0">اصلی</option>--}}
                                {{--@if($category_childs && count($category_childs)>0)--}}
                                    {{--@foreach($category_childs as $child)--}}
                                        {{--<option value="{{ $child->category_id }}">{{ $child->category_title }}</option>--}}

                                    {{--@endforeach--}}
                                {{--@endif--}}

                            {{--</select>--}}
                        </div>
                        <div class="form-group">
                            <label for="attributes">ویژگی ها:</label>
                            {{--@if($attributes && count($attributes) >0)--}}
                                {{--@foreach($attributes as $attribute)--}}
                                    {{--<input type="checkbox" id="attribute" name="attribute_item[]" value="{{$attribute->attribute_id}}">{{$attribute->attribute_name}}--}}
                                {{--@endforeach--}}
                            {{--@endif--}}

                        </div>


                        {{--<div class="form-group">--}}
                        {{--<label for="exampleInputFile">ارسال فایل</label>--}}
                        {{--<input type="file" id="exampleInputFile">--}}

                        {{--<p class="help-block">متن راهنما</p>--}}
                        {{--</div>--}}

                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">ثبت</button>
                    </div>
                </form>
            </div>

@endsection

resources/views/admin/order/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ $title }}</h3>

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post">
                    {{ csrf_field() }}
                    <div class="box-body">
                        <div class="form-group">
                            <label for="category_title">عنوان دسته بندی :</label>
                            <input type="text" class="form-control" id="category_title" name="category_title"
                                   value="{{ $category_info->category_title }}">
                        </div>

                        <div class="form-group">
                            <label for="category_parent_id">سرگروه دسته :</label>
                            <select name="category_parent_id" id="category_parent_id">
                                <option selected
                                value="0">دسته مادر</option>
                                @foreach($all_category as $category)
                                    @if(isset($category_info->parent)  && $category_info->parent->category_id==$category->category_id)
                                        <option selected value=" {{ $category->category_id }}">
                                            {{ $category->category_title }}
                                        </option>
                                    @else
                                        <option  value=" {{ $category->category_id }}">
                                            {{ $category->category_title }}
                                        </option>
                                    @endif

                                @endforeach


                            </select>

                        </div>


                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">ثبت</button>
                    </div>
                </form>
            </div>

@endsection

resources/views/admin/order/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">

                <div class="box-header">
                    <h3 class="box-title">{{ $title }}   </h3>

                    <div class="box-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="table_search" class="form-control pull-right" placeholder="جستجو">

                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tr>
                            <th>کاربر</th>
                            <th>مبلغ کل سفارش</th>
                            <th>کل تخفیف</th>
                            <th>مبلغ قابل پرداخت</th>
                            <th>شیوه پرداخت</th>
                            <th>نوع حمل و نقل</th>
                            <th>هزینه حمل و نقل</th>
                            <th>هزینه بسته بندی</th>
                            <th>تعداد آیتم ها سفارش</th>
                            <th>توضیحات</th>
                            <th>وضعیت</th>
                            <th>عملیات</th>

                        </tr>
                        @if($orders && count($orders)>0)
                            @foreach($orders as $order)
                                <tr>
                                    <td>{{ $order->user->name }}</td>
                                    <td>{{ $order->order_total_amount }}</td>
                                    <td>{{ $order->order_discount }}</td>
                                    <td>{{ $order->order_payable_amount }}</td>
                                    <td>{{ $order->present()->payment_method }}</td>
                                    <td>{{ $order->order_shipping_method }}</td>
                                    <td>{{ $order->order_shipping_amount }}</td>
                                    <td>{{ $order->order_packing_amount }}</td>
                                    <td>{{ $order->order_items->count()}}</td>

                                    <td>{{ $order->order_description }}</td>
                                    <td>{!!  $order->present()->orderStatusHtml !!}</td>
                                    <td>
                                        <a href="">ویرابش</a>
                                        <a href="">حذف</a>
                                    </td>
                                    {!!  $order->present()->opration !!}
                                </tr>

                            @endforeach

                        @endif


                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
@endsection

resources/views/admin/order/opration.blade.php
@if($order->isApproval())
    <td><a href="{{ route('admin.order.approve',[$order->entity->order_id]) }}"><span class="label label-success">تایید شده</span></a></td>
@endif